test: make sure we wait for promises to resolve
Without waiting for promises to resolve, I noticed it's possible to leak
to subsequent tests and error. One example failure:

```
TypeError: Cannot read properties of null (reading 'style')

  at style (node_modules/@artsy/palette/src/elements/Collapse/Collapse.tsx:47:26)
```

This wraps things in a helper so we don't forget.